import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'

export type Language = 'pt' | 'en'

interface AppContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const AppContext = createContext<AppContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navegação
    'nav.home': 'Início',
    'nav.whatisf1': 'O que é F1',
    'nav.rules': 'Regras',
    'nav.teams': 'Equipes',
    'nav.calendar': 'Calendário',
    'nav.points': 'Pontuação',
    'nav.watch': 'Onde Assistir',
    'nav.circuits': 'Circuitos',
    'nav.legends': 'Lendas',
    'nav.tires': 'Pneus',
    'nav.weather': 'Clima',
    'nav.news': 'Notícias',

    // Hero
    'hero.season': 'Temporada',
    'hero.title': 'Descubra o Mundo da',
    'hero.subtitle': 'Tudo o que você precisa saber para acompanhar a categoria mais emocionante do automobilismo. De forma simples, prática e divertida para todas as idades.',
    'hero.cta.rules': 'Novas Regras',
    'hero.cta.news': 'Notícias Ao Vivo',
    'hero.stats.teams': 'Equipes',
    'hero.stats.races': 'Corridas',
    'hero.stats.drivers': 'Pilotos',
    'hero.stats.weight': 'Peso Mínimo',

    // O que é F1
    'whatis.badge': 'Fundamentos',
    'whatis.title': 'O que é a',
    'whatis.subtitle': 'A F1 é a categoria mais avançada do automobilismo. Carros ultrarrápidos, tecnologia de ponta e os melhores pilotos do mundo.',
    'whatis.gp.title': 'Grand Prix',
    'whatis.gp.desc': 'Cada corrida é chamada de Grand Prix (Grande Prêmio). São 24 corridas por ano em países diferentes.',
    'whatis.qualifying.title': 'Qualifying',
    'whatis.qualifying.desc': 'Sessão que define a ordem de largada. O mais rápido larga na frente - chamado de pole position.',
    'whatis.teams.title': 'Equipes',
    'whatis.teams.desc': '11 equipes (construtores) competem, cada uma com 2 pilotos. Total de 22 pilotos no grid.',
    'whatis.points.title': 'Pontuação',
    'whatis.points.desc': 'Os 10 primeiros colocados marcam pontos: 25 – 18 – 15 – 12 – 10 – 8 – 6 – 4 – 2 – 1. Há ainda 1 ponto extra pela volta mais rápida, desde que o piloto termine no top 10.',
    'whatis.weekend.title': 'Como Funciona um Fim de Semana de Corrida',
    'whatis.friday.day': 'Sexta',
    'whatis.friday.title': 'Treinos Livres',
    'whatis.friday.desc': 'Dois treinos de 1h cada para os pilotos testarem o carro e a pista.',
    'whatis.saturday.day': 'Sábado',
    'whatis.saturday.title': 'Qualifying',
    'whatis.saturday.desc': 'Sessão de classificação em três partes (Q1, Q2, Q3) que define o grid de largada.',
    'whatis.sunday.day': 'Domingo',
    'whatis.sunday.title': 'Corrida',
    'whatis.sunday.desc': 'A grande final! Todos largam juntos e quem cruza a linha primeiro vence.',

    // Regras
    'rules.badge': 'Nova Era',
    'rules.title': 'Novas Regras',
    'rules.subtitle': 'marca uma das maiores mudanças na história da F1. Carros menores, mais leves, com aerodinâmica ativa e foco em sustentabilidade.',
    'rules.tab.car': 'Carro',
    'rules.tab.engine': 'Motor',
    'rules.tab.aero': 'Aerodinâmica',
    'rules.tab.safety': 'Segurança',
    'rules.car.title': 'Especificações do Carro',
    'rules.car.weight': 'Peso Mínimo',
    'rules.car.length': 'Comprimento',
    'rules.car.width': 'Largura',
    'rules.car.power': 'Potência',
    'rules.car.tires.title': 'Pneus Mais Estreitos',
    'rules.car.tires.front': 'Dianteiros',
    'rules.car.tires.rear': 'Traseiros',
    'rules.car.drag.title': 'Menos Arrasto',
    'rules.car.drag.desc': 'Redução de 55% no arrasto aerodinâmico, permitindo maior velocidade nas retas.',
    'rules.engine.title': 'Revolução nos Motores',
    'rules.engine.ice': 'Combustão (ICE)',
    'rules.engine.electric': 'Elétrico (MGU-K)',
    'rules.engine.fuel.title': 'Combustível 100% Sustentável',
    'rules.engine.fuel.desc': '"Drop-in" fuel criado de fontes não-alimentares.',
    'rules.engine.energy.title': 'Recuperação de Energia',
    'rules.engine.energy.desc': 'Energia recuperada nas freadas dobrou.',
    'rules.aero.title': 'Aerodinâmica Ativa',
    'rules.aero.x.title': 'Modo X (Retas)',
    'rules.aero.x.desc': 'Asas abertas para mínimo arrasto.',
    'rules.aero.z.title': 'Modo Z (Curvas)',
    'rules.aero.z.desc': 'Asas fechadas para máximo downforce.',
    'rules.aero.drs.title': 'Fim do DRS',
    'rules.aero.drs.badge': 'DRS Eliminado',
    'rules.safety.title': 'Segurança Reforçada',
    'rules.safety.roll.title': 'Roll Hoop +23%',
    'rules.safety.roll.desc': 'A estrutura de proteção do cockpit agora suporta 23% mais carga.',
    'rules.safety.nose.title': 'Nariz em Duas Etapas',
    'rules.safety.nose.desc': 'Novo design do impacto frontal que se separa em duas fases.',
    'rules.safety.lights.title': 'Luzes de Segurança',
    'rules.safety.lights.desc': 'Novas luzes laterais indicam o status do sistema ERS.',

    // Equipes
    'teams.badge': 'Grid',
    'teams.title': 'As',
    'teams.subtitle': 'Conheça todas as equipes que competem na temporada',
    'teams.drivers': 'Pilotos',
    'teams.engine': 'Motor',
    'teams.points': 'Pontos',
    'teams.profile': 'Ver Perfil da Equipe',

    // Calendário
    'calendar.badge': 'Temporada',
    'calendar.title': 'Calendário de',
    'calendar.subtitle': 'Acompanhe todas as datas e horários das corridas da temporada',
    'calendar.official.title': 'Calendário Oficial F1',
    'calendar.official.desc': 'Acesse o calendário completo com todas as datas, horários e circuitos da temporada diretamente no site oficial da Fórmula 1.',
    'calendar.official.cta': 'Ver Calendário Oficial',
    'calendar.circuits': 'Circuitos',
    'calendar.times': 'Horários',
    'calendar.results': 'Resultados',

    // Pontuação
    'points.badge': 'Sistema de Competição',
    'points.title': 'Pontuação &',
    'points.subtitle': 'Entenda como funcionam as classificações e como os pontos são distribuídos.',
    'points.system.title': 'Sistema de Pontuação',
    'points.position': 'Posição',
    'points.fastlap.title': 'Volta Mais Rápida',
    'points.fastlap.desc': '+1 ponto para o piloto que fizer a melhor volta (top 10).',
    'points.qualifying.title': 'Formato do Qualifying',
    'points.q1.time': '18 minutos',
    'points.q1.elim': 'Elimina 5',
    'points.q1.desc': 'Todos os 22 pilotos participam. Os 5 últimos são eliminados.',
    'points.q2.time': '15 minutos',
    'points.q2.elim': 'Elimina 5',
    'points.q2.desc': 'Os 17 restantes competem. Mais 5 eliminados.',
    'points.q3.time': '12 minutos',
    'points.q3.elim': 'Top 10',
    'points.q3.desc': 'Os 12 finalistas disputam as 10 primeiras posições.',
    'points.championships.title': 'Dois Campeonatos Mundiais',
    'points.drivers.title': 'Pilotos',
    'points.drivers.desc': 'Soma de todos os pontos conquistados pelo piloto ao longo da temporada.',
    'points.constructors.title': 'Construtores',
    'points.constructors.desc': 'Soma dos pontos dos dois pilotos de cada equipe.',

    // Onde Assistir
    'watch.badge': 'Transmissão',
    'watch.title': 'Onde',
    'watch.subtitle': 'Descubra onde assistir às corridas de Fórmula 1 ao vivo na TV e streaming.',
    'watch.live': 'Assistir ao vivo',
    'watch.f1tv.title': 'F1 TV Pro - Oficial',
    'watch.f1tv.desc': 'O melhor streaming oficial da Fórmula 1',
    'watch.f1tv.cta': 'Assinar F1 TV Pro',
    'watch.band.type': 'TV Aberta',
    'watch.band.desc': 'Transmissão gratuita de todas as corridas ao vivo.',
    'watch.f1tvpro.type': 'Streaming Oficial',
    'watch.f1tvpro.desc': 'Streaming oficial da F1 com todas as sessões ao vivo e onboard.',
    'watch.espn.type': 'TV por Assinatura',
    'watch.espn.desc': 'Transmissão das corridas em algumas etapas.',
    'watch.star.type': 'Streaming',
    'watch.star.desc': 'Streaming com conteúdo da ESPN incluindo F1.',
    'watch.dazn.type': 'Streaming',
    'watch.dazn.desc': 'Disponível em alguns países com direitos de transmissão.',

    // Circuitos
    'circuits.badge': 'Pistas',
    'circuits.title': 'Circuitos da',
    'circuits.subtitle': 'Conheça os 24 circuitos que recebem as corridas da temporada. Cada um com suas características únicas.',
    'circuits.length': 'Comprimento',
    'circuits.laps': 'Voltas',
    'circuits.seeall': 'Ver Todos os Circuitos',
    'circuits.modal.length': 'Comprimento',
    'circuits.modal.laps': 'Voltas',
    'circuits.modal.seeMore': 'Ver mais sobre',
    'circuits.modal.seeMoreSuffix': '',

    // Galeria
    'gallery.badge': 'Galeria',
    'gallery.title': 'Imagens da',
    'gallery.subtitle': 'Momentos épicos da Fórmula 1 capturados em imagens.',
    'gallery.image1.title': 'Ação na Pista',
    'gallery.image2.title': 'Momento da Vitória',
    'gallery.image3.title': 'Tecnologia de Ponta',

    // Sistema Automatizado
    'auto.badge': 'Como Funciona',
    'auto.title': 'O que é',
    'auto.automated': 'Automatizado',
    'auto.subtitle': 'Entenda o que o site busca automaticamente para você — e o que de fato acontece nos bastidores.',
    'auto.active': 'Ativo',
    'auto.available': 'Disponível',
    'auto.realtime.title': 'Notícias de F1 em Tempo Real',
    'auto.realtime.desc': 'Notícias buscadas de feeds RSS de fontes como Autosport, BBC Sport e ESPN. O site verifica novidades a cada 15 minutos e também automaticamente quando você retorna à página.',
    'auto.year.title': 'Ano da Temporada Dinâmico',
    'auto.year.desc': 'O site detecta o ano atual do navegador e ajusta automaticamente todos os textos, títulos e referências de temporada — sem precisar de atualização manual.',
    'auto.links.title': 'Tradução Automática PT/EN',
    'auto.links.desc': 'As notícias chegam originalmente em inglês e são traduzidas automaticamente para o português usando a API gratuita MyMemory. A qualidade da tradução pode variar conforme o texto.',
    'auto.cache.title': 'Cache Local de 30 Minutos',
    'auto.cache.desc': 'As notícias e a pontuação dos construtores são salvas no cache do seu navegador por 30 minutos. Isso evita requisições desnecessárias e faz o site responder mais rápido.',
    'auto.manual.title': 'Pontuação Oficial dos Construtores',
    'auto.manual.desc': 'A tabela de pontos dos construtores vem diretamente da API Jolpica (dados oficiais Ergast F1). Os dados refletem a classificação real da temporada atual.',

    // Lendas
    'legends.badge': 'Hall da Fama',
    'legends.title': 'Lendas da',
    'legends.subtitle': 'Os pilotos que marcaram época e escreveram a história da Fórmula 1.',
    'legends.titles': 'Títulos',
    'legends.wins': 'Vitórias',
    'legends.poles': 'Poles',
    'legends.podiums': 'Pódios',
    'legends.period': 'F1 Season',
    'legends.viewProfile': 'Ver perfil',
    'legends.schumacher.desc': 'O "Kaiser" detém o recorde de 7 campeonatos mundiais e 91 vitórias.',
    'legends.senna.desc': 'Lenda brasileira conhecida por sua velocidade pura e habilidade na chuva.',
    'legends.hamilton.desc': 'Empatado com Schumacher em títulos, é o recordista de pole positions.',
    'legends.verstappen.desc': 'Campeão de 2021, 2022, 2023 e 2024. Estrela da Red Bull.',
    'legends.prost.desc': 'O "Professor" era conhecido por sua inteligência estratégica.',
    'legends.vettel.desc': 'Tetracampeão com a Red Bull, dominou a F1 de 2010 a 2013.',

    // Pneus
    'tires.badge': 'Compostos',
    'tires.title': 'Sistema de',
    'tires.subtitle': 'Entenda como funcionam os diferentes tipos de pneus e quando usá-los.',
    'tires.soft.title': 'Macio',
    'tires.soft.desc': 'Máximo grip, menor durabilidade. Vermelho.',
    'tires.medium.title': 'Médio',
    'tires.medium.desc': 'Equilíbrio entre performance e durabilidade. Amarelo.',
    'tires.hard.title': 'Duro',
    'tires.hard.desc': 'Maior durabilidade, menos grip. Branco.',
    'tires.inter.title': 'Intermediário',
    'tires.inter.desc': 'Para pista molhada ou secando. Verde.',
    'tires.wet.title': 'Chuva',
    'tires.wet.desc': 'Para pista muito molhada. Azul.',
    'tires.strategy.title': 'Estratégia de Pneus',
    'tires.strategy.rule.title': 'Obrigatoriedade de Compostos',
    'tires.strategy.rule.desc': 'Cada piloto deve usar pelo menos 2 compostos diferentes durante a corrida (seco). A escolha certa pode fazer a diferença entre vencer ou perder.',
    'tires.tip': 'Dica',
    'tires.tip.desc': 'A escolha do momento certo para trocar os pneus pode fazer a diferença!',
    'tires.durability.low': 'Baixa',
    'tires.durability.medium': 'Média',
    'tires.durability.high': 'Alta',
    'tires.durability.variable': 'Variável',

    // Clima
    'weather.badge': 'Condições',
    'weather.title': 'Clima &',
    'weather.subtitle': 'O clima é um fator crucial que pode mudar completamente o resultado de uma corrida.',
    'weather.dry.title': 'Pista Seca',
    'weather.dry.desc': 'Condições ideais. Pneus de seco (macio, médio, duro).',
    'weather.dry.strategy': 'Pneus mais macios',
    'weather.cloudy.title': 'Nublado',
    'weather.cloudy.desc': 'Pista mais fria, menos aderência.',
    'weather.cloudy.strategy': 'Pneus médios',
    'weather.wet.title': 'Pista Molhada',
    'weather.wet.desc': 'Requer pneus de chuva. Maior desafio para pilotos.',
    'weather.wet.strategy': 'Pneus intermediários',
    'weather.heavyRain.title': 'Chuva Forte',
    'weather.heavyRain.desc': 'Pista inundada, visibilidade reduzida.',
    'weather.heavyRain.strategy': 'Pneus de chuva',
    'weather.flags.title': 'Bandeiras Importantes',
    'weather.flag.green': 'Verde',
    'weather.flag.green.desc': 'Pista livre, corrida normal',
    'weather.flag.yellow': 'Amarela',
    'weather.flag.yellow.desc': 'Perigo na pista, proibido ultrapassar',
    'weather.flag.red': 'Vermelha',
    'weather.flag.red.desc': 'Corrida interrompida, parar nos boxes',
    'weather.flag.checkered': 'Xadrez',
    'weather.flag.checkered.desc': 'Fim da corrida!',
    'weather.strategy': 'Estratégia',

    // Notícias
    'news.badge': 'Atualizações',
    'news.title': 'Últimas',
    'news.subtitle': 'Fique por dentro das últimas notícias, resultados e atualizações do mundo da Fórmula 1.',
    'news.live': 'AO VIVO',
    'news.minutes': 'minutos atrás',
    'news.hours': 'horas atrás',
    'news.days': 'dias atrás',
    'news.readmore': 'Ler mais em',
    'news.loading': 'Carregando notícias...',
    'news.error': 'Erro ao carregar notícias',
    'news.updated': 'Agora',
    'news.refresh': 'Atualizar',
    'news.sources': 'Fontes',
    'news.seeLess': 'Ver Menos',
    'news.seeAll': 'Ver Todas',
    'news.sourceLabel': 'Fonte',

    // Footer
    'footer.about': 'Sobre',
    'footer.about.desc': 'F1 Start é o guia definitivo para quem quer entender e acompanhar a Fórmula 1 de forma simples e divertida.',
    'footer.links': 'Links Rápidos',
    'footer.follow': 'Siga a F1',
    'footer.copyright': 'Todos os direitos reservados.',
    'footer.disclaimer': 'F1 Start não é afiliado à Formula 1. F1 é marca registrada da Formula One Licensing B.V.',

    // Idiomas
    'lang.pt': 'Português',
    'lang.en': 'English',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.whatisf1': 'What is F1',
    'nav.rules': 'Rules',
    'nav.teams': 'Teams',
    'nav.calendar': 'Calendar',
    'nav.points': 'Points',
    'nav.watch': 'Where to Watch',
    'nav.circuits': 'Circuits',
    'nav.legends': 'Legends',
    'nav.tires': 'Tires',
    'nav.weather': 'Weather',
    'nav.news': 'News',

    // Hero
    'hero.season': 'Season',
    'hero.title': 'Discover the World of',
    'hero.subtitle': 'Everything you need to know to follow the most exciting category in motorsport. Simple, practical and fun for all ages.',
    'hero.cta.rules': 'New Rules',
    'hero.cta.news': 'Live News',
    'hero.stats.teams': 'Teams',
    'hero.stats.races': 'Races',
    'hero.stats.drivers': 'Drivers',
    'hero.stats.weight': 'Min Weight',

    // O que é F1
    'whatis.badge': 'Fundamentals',
    'whatis.title': 'What is',
    'whatis.subtitle': 'F1 is the most advanced category in motorsport. Ultra-fast cars, cutting-edge technology and the best drivers in the world.',
    'whatis.gp.title': 'Grand Prix',
    'whatis.gp.desc': 'Each race is called a Grand Prix. There are 24 races per year in different countries.',
    'whatis.qualifying.title': 'Qualifying',
    'whatis.qualifying.desc': 'Session that defines the starting order. The fastest starts at the front - called pole position.',
    'whatis.teams.title': 'Teams',
    'whatis.teams.desc': '11 teams (constructors) compete, each with 2 drivers. Total of 22 drivers on the grid.',
    'whatis.points.title': 'Points',
    'whatis.points.desc': 'The top 10 finishers earn points: 25 – 18 – 15 – 12 – 10 – 8 – 6 – 4 – 2 – 1. A bonus point is also awarded for the fastest lap, as long as the driver finishes in the top 10.',
    'whatis.weekend.title': 'How a Race Weekend Works',
    'whatis.friday.day': 'Friday',
    'whatis.friday.title': 'Free Practice',
    'whatis.friday.desc': 'Two 1-hour sessions for drivers to test the car and track.',
    'whatis.saturday.day': 'Saturday',
    'whatis.saturday.title': 'Qualifying',
    'whatis.saturday.desc': 'Three-part qualifying session (Q1, Q2, Q3) that defines the starting grid.',
    'whatis.sunday.day': 'Sunday',
    'whatis.sunday.title': 'Race',
    'whatis.sunday.desc': 'The grand finale! Everyone starts together and whoever crosses the line first wins.',

    // Regras
    'rules.badge': 'New Era',
    'rules.title': 'New Rules',
    'rules.subtitle': 'marks one of the biggest changes in F1 history. Smaller, lighter cars with active aerodynamics and focus on sustainability.',
    'rules.tab.car': 'Car',
    'rules.tab.engine': 'Engine',
    'rules.tab.aero': 'Aerodynamics',
    'rules.tab.safety': 'Safety',
    'rules.car.title': 'Car Specifications',
    'rules.car.weight': 'Min Weight',
    'rules.car.length': 'Length',
    'rules.car.width': 'Width',
    'rules.car.power': 'Power',
    'rules.car.tires.title': 'Narrower Tires',
    'rules.car.tires.front': 'Front',
    'rules.car.tires.rear': 'Rear',
    'rules.car.drag.title': 'Less Drag',
    'rules.car.drag.desc': '55% reduction in aerodynamic drag, allowing higher speeds on straights.',
    'rules.engine.title': 'Engine Revolution',
    'rules.engine.ice': 'Combustion (ICE)',
    'rules.engine.electric': 'Electric (MGU-K)',
    'rules.engine.fuel.title': '100% Sustainable Fuel',
    'rules.engine.fuel.desc': '"Drop-in" fuel created from non-food sources.',
    'rules.engine.energy.title': 'Energy Recovery',
    'rules.engine.energy.desc': 'Energy recovered from braking has doubled.',
    'rules.aero.title': 'Active Aerodynamics',
    'rules.aero.x.title': 'Mode X (Straights)',
    'rules.aero.x.desc': 'Wings open for minimum drag.',
    'rules.aero.z.title': 'Mode Z (Corners)',
    'rules.aero.z.desc': 'Wings closed for maximum downforce.',
    'rules.aero.drs.title': 'End of DRS',
    'rules.aero.drs.badge': 'DRS Eliminated',
    'rules.safety.title': 'Enhanced Safety',
    'rules.safety.roll.title': 'Roll Hoop +23%',
    'rules.safety.roll.desc': 'The cockpit protection structure now supports 23% more load.',
    'rules.safety.nose.title': 'Two-Stage Nose',
    'rules.safety.nose.desc': 'New front impact design that separates in two phases.',
    'rules.safety.lights.title': 'Safety Lights',
    'rules.safety.lights.desc': 'New side lights indicate ERS system status.',

    // Equipes
    'teams.badge': 'Grid',
    'teams.title': 'The',
    'teams.subtitle': 'Meet all the teams competing in the season',
    'teams.drivers': 'Drivers',
    'teams.engine': 'Engine',
    'teams.points': 'Points',
    'teams.profile': 'View Team Profile',

    // Calendário
    'calendar.badge': 'Season',
    'calendar.title': 'Race',
    'calendar.subtitle': 'Follow all dates and times for the season races',
    'calendar.official.title': 'Official F1 Calendar',
    'calendar.official.desc': 'Access the complete calendar with all dates, times and circuits for the season directly on the official Formula 1 website.',
    'calendar.official.cta': 'View Official Calendar',
    'calendar.circuits': 'Circuits',
    'calendar.times': 'Times',
    'calendar.results': 'Results',

    // Pontuação
    'points.badge': 'Competition System',
    'points.title': 'Points &',
    'points.subtitle': 'Understand how classifications work and how points are distributed.',
    'points.system.title': 'Points System',
    'points.position': 'Position',
    'points.fastlap.title': 'Fastest Lap',
    'points.fastlap.desc': '+1 point for the driver with the best lap (top 10).',
    'points.qualifying.title': 'Qualifying Format',
    'points.q1.time': '18 minutes',
    'points.q1.elim': 'Eliminates 5',
    'points.q1.desc': 'All 22 drivers participate. Bottom 5 are eliminated.',
    'points.q2.time': '15 minutes',
    'points.q2.elim': 'Eliminates 5',
    'points.q2.desc': 'Remaining 17 compete. 5 more eliminated.',
    'points.q3.time': '12 minutes',
    'points.q3.elim': 'Top 10',
    'points.q3.desc': 'Top 12 finalists compete for the first 10 positions.',
    'points.championships.title': 'Two World Championships',
    'points.drivers.title': 'Drivers',
    'points.drivers.desc': 'Sum of all points earned by the driver throughout the season.',
    'points.constructors.title': 'Constructors',
    'points.constructors.desc': 'Sum of points from both drivers of each team.',

    // Onde Assistir
    'watch.badge': 'Broadcast',
    'watch.title': 'Where to',
    'watch.subtitle': 'Discover where to watch Formula 1 races live on TV and streaming.',
    'watch.live': 'Watch live',
    'watch.f1tv.title': 'F1 TV Pro - Official',
    'watch.f1tv.desc': 'The best official Formula 1 streaming service',
    'watch.f1tv.cta': 'Subscribe to F1 TV Pro',
    'watch.band.type': 'Free TV',
    'watch.band.desc': 'Free broadcast of all races live.',
    'watch.f1tvpro.type': 'Official Streaming',
    'watch.f1tvpro.desc': 'Official F1 streaming with all sessions live and onboard.',
    'watch.espn.type': 'Cable TV',
    'watch.espn.desc': 'Broadcast of races at some stages.',
    'watch.star.type': 'Streaming',
    'watch.star.desc': 'Streaming with ESPN content including F1.',
    'watch.dazn.type': 'Streaming',
    'watch.dazn.desc': 'Available in some countries with broadcast rights.',

    // Circuitos
    'circuits.badge': 'Tracks',
    'circuits.title': 'Circuits',
    'circuits.subtitle': 'Discover the 24 circuits that host the season races. Each with its unique characteristics.',
    'circuits.length': 'Length',
    'circuits.laps': 'Laps',
    'circuits.seeall': 'View All Circuits',
    'circuits.modal.length': 'Length',
    'circuits.modal.laps': 'Laps',
    'circuits.modal.seeMore': 'See more about',
    'circuits.modal.seeMoreSuffix': '',

    // Galeria
    'gallery.badge': 'Gallery',
    'gallery.title': 'Images of',
    'gallery.subtitle': 'Epic moments from Formula 1 captured in images.',
    'gallery.image1.title': 'Track Action',
    'gallery.image2.title': 'Victory Moment',
    'gallery.image3.title': 'Cutting Edge Technology',

    // Sistema Automatizado
    'auto.badge': 'How It Works',
    'auto.title': 'What is',
    'auto.automated': 'Automated',
    'auto.subtitle': 'Understand what the site fetches automatically — and what actually happens behind the scenes.',
    'auto.active': 'Active',
    'auto.available': 'Available',
    'auto.realtime.title': 'F1 News in Real Time',
    'auto.realtime.desc': 'News fetched from RSS feeds from sources like Autosport, BBC Sport and ESPN. The site checks for updates every 15 minutes and also automatically when you return to the page.',
    'auto.year.title': 'Dynamic Season Year',
    'auto.year.desc': 'The site reads the current year from the browser and automatically updates all texts, titles and season references — no manual update needed.',
    'auto.links.title': 'Automatic PT/EN Translation',
    'auto.links.desc': 'News originally arrives in English and is automatically translated to Portuguese using the free MyMemory API. Translation quality may vary depending on the text.',
    'auto.cache.title': '30-Minute Local Cache',
    'auto.cache.desc': 'News and constructor standings are saved in your browser cache for 30 minutes. This avoids unnecessary requests and makes the site respond faster.',
    'auto.manual.title': 'Official Constructor Standings',
    'auto.manual.desc': 'The constructor points table comes directly from the Jolpica API (official Ergast F1 data). The data reflects the real standings of the current season.',

    // Lendas
    'legends.badge': 'Hall of Fame',
    'legends.title': 'Legends of',
    'legends.subtitle': 'The drivers who marked an era and wrote the history of Formula 1.',
    'legends.titles': 'Titles',
    'legends.wins': 'Wins',
    'legends.poles': 'Poles',
    'legends.podiums': 'Podiums',
    'legends.period': 'F1 Season',
    'legends.viewProfile': 'View profile',
    'legends.schumacher.desc': 'The "Kaiser" holds the record of 7 world championships and 91 wins.',
    'legends.senna.desc': 'Brazilian legend known for his pure speed and skill in the rain.',
    'legends.hamilton.desc': 'Tied with Schumacher in titles, he is the record holder of pole positions.',
    'legends.verstappen.desc': 'Champion of 2021, 2022, 2023 and 2024. Red Bull star.',
    'legends.prost.desc': 'The "Professor" was known for his strategic intelligence.',
    'legends.vettel.desc': 'Four-time champion with Red Bull, dominated F1 from 2010 to 2013.',

    // Pneus
    'tires.badge': 'Compounds',
    'tires.title': 'Tire',
    'tires.subtitle': 'Understand how the different tire types work and when to use them.',
    'tires.soft.title': 'Soft',
    'tires.soft.desc': 'Maximum grip, lower durability. Red.',
    'tires.medium.title': 'Medium',
    'tires.medium.desc': 'Balance between performance and durability. Yellow.',
    'tires.hard.title': 'Hard',
    'tires.hard.desc': 'Greater durability, less grip. White.',
    'tires.inter.title': 'Intermediate',
    'tires.inter.desc': 'For wet or drying track. Green.',
    'tires.wet.title': 'Wet',
    'tires.wet.desc': 'For very wet track. Blue.',
    'tires.strategy.title': 'Tire Strategy',
    'tires.strategy.rule.title': 'Compound Requirement',
    'tires.strategy.rule.desc': 'Each driver must use at least 2 different compounds during the race (dry). The right choice can make the difference between winning or losing.',
    'tires.tip': 'Tip',
    'tires.tip.desc': 'Choosing the right time to change tires can make the difference!',
    'tires.durability.low': 'Low',
    'tires.durability.medium': 'Medium',
    'tires.durability.high': 'High',
    'tires.durability.variable': 'Variable',

    // Clima
    'weather.badge': 'Conditions',
    'weather.title': 'Weather &',
    'weather.subtitle': 'Weather is a crucial factor that can completely change the outcome of a race.',
    'weather.dry.title': 'Dry Track',
    'weather.dry.desc': 'Ideal conditions. Dry tires (soft, medium, hard).',
    'weather.dry.strategy': 'Softer tires',
    'weather.cloudy.title': 'Cloudy',
    'weather.cloudy.desc': 'Colder track, less grip.',
    'weather.cloudy.strategy': 'Medium tires',
    'weather.wet.title': 'Wet Track',
    'weather.wet.desc': 'Requires wet tires. Greater challenge for drivers.',
    'weather.wet.strategy': 'Intermediate tires',
    'weather.heavyRain.title': 'Heavy Rain',
    'weather.heavyRain.desc': 'Flooded track, reduced visibility.',
    'weather.heavyRain.strategy': 'Wet tires',
    'weather.flags.title': 'Important Flags',
    'weather.flag.green': 'Green',
    'weather.flag.green.desc': 'Track clear, normal race',
    'weather.flag.yellow': 'Yellow',
    'weather.flag.yellow.desc': 'Danger on track, no overtaking',
    'weather.flag.red': 'Red',
    'weather.flag.red.desc': 'Race stopped, go to pits',
    'weather.flag.checkered': 'Checkered',
    'weather.flag.checkered.desc': 'End of race!',
    'weather.strategy': 'Strategy',

    // Notícias
    'news.badge': 'Updates',
    'news.title': 'Latest',
    'news.subtitle': 'Stay up to date with the latest news, results and updates from the world of Formula 1.',
    'news.live': 'LIVE',
    'news.minutes': 'minutes ago',
    'news.hours': 'hours ago',
    'news.days': 'days ago',
    'news.readmore': 'Read more at',
    'news.loading': 'Loading news...',
    'news.error': 'Error loading news',
    'news.updated': 'Now',
    'news.refresh': 'Refresh',
    'news.sources': 'Sources',
    'news.seeLess': 'See Less',
    'news.seeAll': 'See All',
    'news.sourceLabel': 'Source',

    // Footer
    'footer.about': 'About',
    'footer.about.desc': 'F1 Start is the definitive guide for those who want to understand and follow Formula 1 in a simple and fun way.',
    'footer.links': 'Quick Links',
    'footer.follow': 'Follow F1',
    'footer.copyright': 'All rights reserved.',
    'footer.disclaimer': 'F1 Start is not affiliated with Formula 1. F1 is a registered trademark of Formula One Licensing B.V.',

    // Idiomas
    'lang.pt': 'Português',
    'lang.en': 'English',
  },
}

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('f1-language') as Language
      return saved || 'pt'
    }
    return 'pt'
  })

  useEffect(() => {
    localStorage.setItem('f1-language', language)
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || key
  }

  return (
    <AppContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </AppContext.Provider>
  )
}

export function useApp() {
  const context = useContext(AppContext)
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider')
  }
  return context
}
